cloudgoat_public_bucket_name = "cloudgoat_bucket_public"
cloudgoat_private_bucket_name = "cloudgoat_bucket_private"
lightsail_keypair = "joes_laptop"
guardduty_email = "joe@example.com"
#aws_region = "us-east-1"
#availability_zone = "us-west-2b"
#ami_id = "ami-xxxxxxxx"
